global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'gitlab-pi-monitor'

rule_files:
  - '/etc/prometheus/alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'gitlab'
    scheme: http
    metrics_path: '/-/metrics'
    static_configs:
      - targets: ['gitlab:8081']

