groups:
  - name: system_alerts
    interval: 30s
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% (current value: {{ $value }}%)"

      - alert: HighMemoryUsage
        expr: 100 * (1 - ((node_memory_MemAvailable_bytes) / (node_memory_MemTotal_bytes))) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% (current value: {{ $value }}%)"

      - alert: LowDiskSpace
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk usage is above 85% (current value: {{ $value }}%)"

      - alert: CriticalDiskSpace
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 95
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "CRITICAL: Very low disk space on {{ $labels.instance }}"
          description: "Disk usage is above 95% (current value: {{ $value }}%)"

      - alert: HighTemperature
        expr: node_hwmon_temp_celsius > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU temperature on {{ $labels.instance }}"
          description: "CPU temperature is above 80째C (current value: {{ $value }}째C)"

      - alert: CriticalTemperature
        expr: node_hwmon_temp_celsius > 85
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "CRITICAL: CPU temperature very high on {{ $labels.instance }}"
          description: "CPU temperature is above 85째C (current value: {{ $value }}째C)"

  - name: gitlab_alerts
    interval: 30s
    rules:
      - alert: GitLabDown
        expr: up{job="gitlab"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "GitLab is down"
          description: "GitLab has been down for more than 2 minutes"

      - alert: GitLabHighMemory
        expr: process_resident_memory_bytes{job="gitlab"} > 3000000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "GitLab using high memory"
          description: "GitLab memory usage is above 3GB (current: {{ $value | humanize }}B)"

      - alert: RunnerDown
        expr: up{job="gitlab-runner"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "GitLab Runner is down"
          description: "GitLab Runner has been down for more than 5 minutes"

  - name: docker_alerts
    interval: 30s
    rules:
      - alert: ContainerDown
        expr: up == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.job }} is down"
          description: "Container has been down for more than 2 minutes"

      - alert: HighContainerMemory
        expr: container_memory_usage_bytes{name!=""} > 1000000000
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Container {{ $labels.name }} using high memory"
          description: "Memory usage: {{ $value | humanize }}B"

  - name: dr_alerts
    interval: 30s
    rules:
      - alert: PiSystemDown
        expr: up{job="node-exporter"} == 0
        for: 3m
        labels:
          severity: critical
          action: "trigger_dr"
        annotations:
          summary: "Pi system is down - triggering DR"
          description: "Node exporter has been down for more than 3 minutes. Activating disaster recovery."

      - alert: GitLabCriticalDown
        expr: up{job="gitlab"} == 0
        for: 3m
        labels:
          severity: critical
          action: "trigger_dr"
        annotations:
          summary: "GitLab critical failure - triggering DR"
          description: "GitLab has been down for more than 3 minutes. Activating disaster recovery."

      - alert: MultipleServicesDown
        expr: (up{job="gitlab"} == 0) + (up{job="prometheus"} == 0) + (up{job="grafana"} == 0) >= 2
        for: 2m
        labels:
          severity: critical
          action: "trigger_dr"
        annotations:
          summary: "Multiple services down - triggering DR"
          description: "Multiple critical services are down. Activating disaster recovery."

      - alert: PiRecovered
        expr: up{job="node-exporter"} == 1 and up{job="gitlab"} == 1
        for: 1m
        labels:
          severity: info
          action: "recover_dr"
        annotations:
          summary: "Pi system recovered - deactivating DR"
          description: "Pi system is back online. Deactivating disaster recovery and syncing data."

      - alert: HeartbeatMissing
        expr: time() - node_boot_time_seconds > 300 and (up{job="node-exporter"} == 0 or absent(up{job="node-exporter"}))
        for: 1m
        labels:
          severity: critical
          action: "trigger_dr"
        annotations:
          summary: "Pi heartbeat missing - triggering DR"
          description: "No heartbeat from Pi system for more than 5 minutes. Activating disaster recovery."

